enum DOME_CMD {DOME_MANUAL, LEFT, RIGHT};
enum COVER_CMD {COVER_MANUAL, OPEN, CLOSE};
enum LIGHT_STATE {OFF, RED, WHITE};
//enum BTN {BTN_UP, BTN_LEFT, BTN_RIGHT, BTN_DOWN, BTN_STOP, BTN_LIGHT};
void comm();